### ISSUE TITLE
split world.cfg into local and global

### ISSUE THREAD

**Issue by stromnet** [M-o-a-T/owslave#1]
Would it be possible to split world.cfg into a local file, where i.e. my devices are located, and a global file where all definitions of i.e. ds2423 and other stuff is located?
This would simplify merges in the future, and avoid accidental commits of private device configurations.

Also, `write_eeprom` expects a `moat.cfg`, unless CFG env var is set. Should this not be `world.cfg`?

**Comment by smurfix** [comment]
On 27.05.2015 08:02, Johan Ström wrote:

> Would it be possible to split world.cfg into a local file, where i.e.
> my devices are located, and a global file where all definitions of
> i.e. ds2423 and other stuff is located?
> 
> Feel free to implement an _include directive. ;-)
> Also, |write_eeprom| expects a |moat.cfg|, unless CFG env var is set.
> Should this not be |world.cfg|? 
> Right.

## 

-- Matthias Urlichs

**Comment by smurfix** [comment]
_include directive added.
