### ISSUE TITLE
PWM never clears alert?

### ISSUE THREAD

**Issue by stromnet** [M-o-a-T/owslave#15]
While writing some new (separate) LED code I've been looking over the PWM code. I noticed PWM_IS_ALERT is set but never cleared, so that probably doesn't work as intended?

**Comment by smurfix** [comment]
On 04.12.2016 22:18, Johan Ström wrote:
>
> While writing some new (separate) LED code I've been looking over the
> PWM code. I noticed PWM_IS_ALERT is set but never cleared, so that
> probably doesn't work as intended?
>
You're right.

Should be cleared in moat_pwm.c:pread_pwm().

Something like this (untested…) will probably work:

diff --git a/moat_pwm.c b/moat_pwm.c

index d070fa4..3f5cdda 100644

--- a/moat_pwm.c

+++ b/moat_pwm.c

@@ -63,8 +63,9 @@ void read_pwm(uint8_t chan, uint8_t *buf)

                for(i=0;i<N_PWM;i++,t++) {

                        uint16_t tm;

                        if(!(i&7)) {

-                               p = &ports[t->port-1];

                                uint8_t j,v=0,m=1;

+                               p = &ports[t->port-1];

+                               t->flags &= ~PWM_IS_ALERT;

                                for(j=0;j<8;j++) {

                                        if (i+j >= N_PWM) break;

                                        if (p->flags & PFLG_CURRENT)


-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
On 04.12.2016 22:48, Matthias Urlichs wrote:
> On 04.12.2016 22:18, Johan Ström wrote:
>> While writing some new (separate) LED code I've been looking over the
>> PWM code. I noticed PWM_IS_ALERT is set but never cleared, so that
>> probably doesn't work as intended?
>>
> You're right.
>
> Should be cleared in moat_pwm.c:pread_pwm().
>
> Something like this (untested…) will probably work:
Improved patch pushed. #fd88868


-- 
-- Matthias Urlichs
