### ISSUE TITLE
onewire_poll blocks for extended period of times

### ISSUE THREAD

**Issue by stromnet** [M-o-a-T/owslave#7]
Hi,

first of all, great work! Overall this works perfectly fine, much better than the older versions of "owslave".

When testing the counters on the mega8 (#6), I benchmarked using my pulse generator, and noticed that even with a 30ms/170ms on/off cycle (i.e. 5 pulses/second), it seemed to miss quite a few.
After some debugging, and adding an extra DBG pin which toggles on entry in `moat_poll()`, I noticed that it will block for quite some time. In some cases, forever.

In my normal operation mode, with alarm scan every 0.2s, it blocks for about 17-18ms between RESET and reception of the ALARM SEARCH command. First channel shows the toggling pin, second the 1w bus:
![screen shot 2015-11-07 at 22 13 40](https://cloud.githubusercontent.com/assets/668449/11017366/e3361cc0-859c-11e5-8cdd-d13152b64010.png)
If I have no alarms, it goes back to polling immediately, until next reset is received:
![screen shot 2015-11-07 at 22 13 19](https://cloud.githubusercontent.com/assets/668449/11017367/e6962540-859c-11e5-8c58-a09c553aa047.png)

But if there _is_ an alarm condition, it will send it's ROM and then wait for command until next RESET:
![screen shot 2015-11-07 at 22 16 37](https://cloud.githubusercontent.com/assets/668449/11017384/4d8857b4-859d-11e5-9ed8-123281b13c49.png)

Normally, my master software will try to react to the alerts immediately (and thus produce further bus traffic), but there will always be some delays.

The issue is that we are stuck in `while(_onewire_poll()) ;` in `onewire_poll(void)`. Any plans or thoughts on restoring update_idle, and possibly use that?
On my 8MHz mega8 during bus idle, `moat_poll` seems to be called every ~9-27 uS, thus the actual execution time is somewhat shorter. This is with adc, port, count, and alarms enabled. Would that mean  it might be doable to do a `moat_poll` run in one bit slot (`update_idle(1)`)?

Regards
Johan

**Comment by smurfix** [comment]
On 07.11.2015 22:30, Johan Ström wrote:

> But if there /is/ an alarm condition, it will send it's ROM and then
> wait for command until next RESET:
> _its_ ROM. :-P

The idea behind conditional read is to have the device in question
pre-selected so that the next command can be sent immediately. In
practice this doesn't happen, owserver doesn't work that way. Thus I'm
OK with accepting a patch to change that (perhaps depending on a
compiler flag).

Onewire timing is finicky. My previous attempt to use the update_idle
loop proved unsatisfactory because the code took too much time and
missed the next byte slot. On the other hand, by now the poll code has
been rewritten to spend as little time during each iteration as
possible, so if you want to resurrect that (and test it!) I'd accept it.

it might be best to only do idle processing when the master is not
currently sending (i.e. the bit counter is zero).

## 

-- Matthias Urlichs

**Comment by stromnet** [comment]
Great, I'll do some testing and see what I come up with!
If nothing else, a after-conditional-response patch should help quite a bit. On a smarter master (i.e. LinkUSB with dedicated search algorithm) the delay between reset and search command would also be much shorter, compared to the one measured above (DS2480B, which roundtrips to owserver before sending search cmd), minimizing the large part of the delay.

**Comment by stromnet** [comment]
A quick test so far, with good results:

```
diff --git a/onewire.c b/onewire.c
index 0eb27a1..e80cc1b 100644
--- a/onewire.c
+++ b/onewire.c
@@ -113,7 +113,7 @@ void _wait_complete(void)
                        return;
                }
                uart_poll();
-               update_idle(1); // actbit
+               update_idle((mode == OWM_IDLE || bitp <= 0x02) ? 8 : 1); // actbit
        }
 }

@@ -343,9 +343,6 @@ char _onewire_poll(void) {
                sei();
        }

-       // RESET processing takes longer.
-       // update_idle((mode == OWM_SLEEP) ? 100 : (mode <= OWM_AFTER_RESET) ? 20 : (mode < OWM_IDLE) ? 8 : 1); // TODO
-
        if (mode == OWM_IDLE) {
                DBG(0x10);
                set_idle();
@@ -354,12 +351,22 @@ char _onewire_poll(void) {
                DBG(0x2F);
                return 0;
        }
+
+       // RESET processing takes longer.
+       update_idle((mode == OWM_SLEEP) ? 100 :
+                       (mode <= OWM_AFTER_RESET) ? 20 :
+                       (mode < OWM_IDLE || bitp == 0x1) ? 8 :
+                               1);
+
        return 1;
 }

diff --git a/moat.c b/moat.c
index 7cd9951..3f00631 100644
--- a/moat.c
+++ b/moat.c
@@ -269,6 +269,11 @@ void do_command(uint8_t cmd)

 void update_idle(uint8_t bits)
 {
+       if(bits < 8) return;
+       DDRD|=(1<<6);
+       PORTD|=(1<<6);
+       moat_poll();
+       PORTD&=~(1<<6);
 }

 #if CONSOLE_PING
```

This will only skip the `moat_poll()` calls while reading bit 2-7 in a READ, or during writing (so about 7_60 = 0.42ms):
![screen shot 2015-11-08 at 22 48 51](https://cloud.githubusercontent.com/assets/668449/11022890/01135770-866b-11e5-909e-3ad5a41d20c7.png)
(On each *non-ignored_ entry into update_idle I set the corresponding debug line, then clear it on exit, as shown in diff above. The same code, not shown, is added in moat_poll & onewire_poll. moat_poll is logged separately since it is called from mainloop too)

Although.. I'm not really sure that it is necessary to avoid polling during subsequent bits, now that the poll's are so fast.
Here showing more detailed how long the update_idle calls take.. not very long!

![screen shot 2015-11-08 at 22 50 27](https://cloud.githubusercontent.com/assets/668449/11022898/22e9237a-866b-11e5-81b4-a16320ef5b63.png)

An overview of the device during a few seconds, the master alarm-scans every 0.2s, if it sees an alarm, it will read alarm + read the count input (which is trigged by "pulse input"):
![screen shot 2015-11-08 at 22 53 00](https://cloud.githubusercontent.com/assets/668449/11022919/94d3e6f0-866b-11e5-91d0-23ce9f67c634.png)
As you can see, moat_poll is more or less called all the time.

**Comment by stromnet** [comment]
I'm trying to recall which part of the bus transacations are the most critical.. Was it write-low (due to late rising edge from our end) + immediate following bitslot? But both of these are controlled via interrupt (timer to release LOW condition, INTn to detect new bitslot). preparing the subsequent bit (in the same byte) is also done in interrupt. Sampling in read is done in interrupt. 

The most tight spot should be at the end of each byte, where we need to process/setup the next byte to be written, right? So, assuming a moat_poll is <30us, avoiding to execute it when bitp is  >= (1<<6) might be enough?
Am I missing something else?

**Comment by smurfix** [comment]
On 11/09/2015 08:18 AM, Johan Ström wrote:

> The most tight spot should be at the end of each byte, where we need 
> to process/setup the next byte to be written, right?
> Actually the most-tight spot, at least in theory, is a write followed by 
> a read (as seen by the slave). Fortunately, the 1wire master controllers 
> are all really dumb, so that there's an intrinsic delay while the master 
> sets up the next part of the bus transfer. If we ever have "fast" 
> masters, owfs/MoaT will probably require a couple of sub-msec delay calls.

Otherwise I agree with you. This should be sufficient.

NB: as far as I recall, one additional reason for initially dropping the 
polling was code size – I barely managed to squeeze a bare-bones counter 
into 4k of flash, deleting all these conditionals. We might want to mask 
these with a "super-minimal-size" ifdef.

## 

-- Matthias Urlichs

**Comment by stromnet** [comment]
So, I've done some changes and the patch is now:
https://gist.github.com/stromnet/a1cd1c2ec75fc944fec4

Reset + presence:
![screen shot 2015-11-09 at 22 06 46](https://cloud.githubusercontent.com/assets/668449/11046514/32946456-872e-11e5-8655-3557662d0314.png)
`moat_poll` runs next to `onewire_poll` until the RESET condition is almost over, at which time `update_idle` starts to trigger `moat_poll` instead.

![screen shot 2015-11-09 at 22 08 26](https://cloud.githubusercontent.com/assets/668449/11046560/6d3b71ee-872e-11e5-9b16-569352eb9c31.png)
During read, we hold of the longer `update_idle` call during the last bit.

![screen shot 2015-11-09 at 22 11 49](https://cloud.githubusercontent.com/assets/668449/11046655/e72ea372-872e-11e5-8ea9-9c0813d43bf8.png)
Same thing during a write. 

As you say, the write 0 + read would be trickiest. I recall the old impl had issues with that during search, but that should be no problem now with no rising interrupt?

Anyway, I'm going to do some testing with my LinkUSB tomorrow as well (this was DS2480B) and check that it works fine. 
Anything else you suggest I take a closer look at?

**Comment by stromnet** [comment]
Oh, and, I've built test_ds2423 _including_ the debug pins in my diff:

```
$ avr-size device/test_ds2423/image.elf
   text    data     bss     dec     hex filename
   3354      49      39    3442     d72 device/test_ds2423/image.elf
```

**Comment by stromnet** [comment]
Seems perfectly fine on the LinkUSB as well. Been running for ~2.5h now, with the moat counter being triggered 10 times per second, master alarmscanning every 0.2s, and reading as soon as it sees the alarm. Not a single read/dir error, and no crc errors registered.

Just started with a longer cable (~200m or so in a box). Will probably work equally fine, this is what the DS2480B master has been connected with all the time!

**Comment by stromnet** [comment]
Running 10h with longer cable, no issues at all.
The DS2480B master ran for 20h+ without issues as well.

**Comment by stromnet** [comment]
Closing this as the change is now merged. @smurfix please test to make sure it works for you too!
